### PR TITLE
Pin the revision for libadwaita

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by lainsce** [comment]
Build failed, might wanna fix that.

Also, didn't I say that I would only pin libadwaita when it gets stable? Why are you dismissing my words?

Not pinning libadwaita right now won't hurt people downloading the flatpak because the flatpakref is frozen to the libadwaita that was used to build the last Colorway version, and there are tools to update it externally if so desired, as seen in the PR I made to include Colorway to flathub.

**Comment by hfiguiere** [comment]
build failed because GNOME gitlab decided to take the night off.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
> Also, didn't I say that I would only pin libadwaita when it gets stable? Why are you dismissing my words?

you dismissed the fact that the build MUST be reproducible. This detail was missed before merging.

**Comment by lainsce** [comment]
> > Also, didn't I say that I would only pin libadwaita when it gets stable? Why are you dismissing my words?
> 
> you dismissed the fact that the build MUST be reproducible. This detail was missed before merging.

And it is reproducible. The build will fail if the versioning of the platform is changed to be lower or the app archive version is changed to be lower. Staying as-is or bumping the version to a higher one makes another reproducible build because libadwaita is cached per app version.

**Comment by lainsce** [comment]
But I'll not argue further and will just accept the PR to make _you_ happy with this weirdly specific imposition even after extensively said that it was ok to stay the old way due to the library in question not being stable yet to pin it properly.

**Pull request merged**
